version: 2
updates:

  # Front end
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"

  # API
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
