services:

  wca-database:
    image: mysql
    restart: always
    volumes:
      - ../databases/wca:/var/lib/mysql
    ports:
      - 4204:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wca
      MYSQL_USER: wca
      MYSQL_PASSWORD: wca

  cubingza-database:
    image: mongo
    restart: always
    volumes:
      - ../databases/cubingza:/data/db
    ports:
      - 4203:27017
    networks:
      - api-database

  cubingza-api:
    build: ./server
    restart: always
    ports:
      - 4202:9000
    networks:
      - website-api
      - api-database
    environment:
      - NODE_ENV=production
      - PORT=9000
      - MONGO_URL=mongodb://cubingza-database:27017
      - MONGODB_URI=mongodb://cubingza-database/cubingza
    env_file:
      - ./server/config/production.env

  cubingza-website:
    build: ./client
    restart: always
    ports:
      - 4201:80
    networks:
      - website-api

networks:
  website-api:
    driver: bridge
  api-database:
    driver: bridge
